### ISSUE TITLE
Getting pyspark to work on HDP 2.3.4

### ISSUE THREAD

**Issue by bernhard-42** [hortonworks-gallery/ambari-zeppelin-service#10]
for %pyspark zeppelin did not find module 'pyspark' (Error from python worker: /usr/bin/python: No module named pyspark)
I had to add 

    export PYTHONPATH="${SPARK_HOME}/python:${SPARK_HOME}/python/lib/py4j-0.8.2.1-src.zip"  
    export SPARK_YARN_USER_ENV="PYTHONPATH=${PYTHONPATH}"

to the `zeppelin-env template` configuration.

(Thanks to http://mail-archives.apache.org/mod_mbox/incubator-zeppelin-users/201506.mbox/%3CCAFX-kxKR+1R11WoG69sa-63nwTcfT1VYFocJBywh6m0q72WqBg@mail.gmail.com%3E)

**Comment by abajwa-hw** [comment]
Updated...thanks!
