### ISSUE TITLE
setup_snapshot.sh

### ISSUE THREAD

**Issue by fabianrc** [hortonworks-gallery/ambari-zeppelin-service#12]
The setup_snapshot.sh return ${SETUP_VIEW,,}: bad substitution; which commenting it solve the issue, also it is trying to execute 
"/var/lib/ambari-agent/cache/stacks/HDP/2.3/services/zeppelin-stack/package/scripts/setup_snapshot.sh /opt/incubator-zeppelin HOST 9083 HOST 9995 True" and the validation is with "true" lowercase and it never configure the ambari view.
Tested on
OS: SUSE Linux Enterprise Server 11 SP3
HDP: 2.3.0.0-2557

**Comment by yogeshtewari** [comment]
I too got the same error.
commenting SETUP_VIEW did the trick.

Tested on
OS: SUSE Linux Enterprise Server 11 SP3
HDP: 2.3.0.0-2557

**Comment by abajwa-hw** [comment]
This should be fixed with below commit
https://github.com/hortonworks-gallery/ambari-zeppelin-service/commit/9b69d1da761108d4cb0b978d05a0ba0d51c7662a

Let us know if you still have issues
