### ISSUE TITLE
Zeppelin deployment in the host that has no internet or git support

### ISSUE THREAD

**Issue by analog76** [hortonworks-gallery/ambari-zeppelin-service#23]
Hi,

I would like to deploy the zeppelin service in the HDP 2.4 platform.   
My data platform doesn't have internet connection or git on that host. How do I deploy this on that platform ? 

Here the steps are not correct or I am missing something. 

VERSION=`hdp-select status hadoop-client | sed 's/hadoop-client - \([0-9]\.[0-9]\).*/\1/'`

sudo git clone https://github.com/hortonworks-gallery/ambari-zeppelin-service.git   /var/lib/ambari-server/resources/stacks/HDP/$VERSION/services/ZEPPELIN

**Comment by abajwa-hw** [comment]
If you don’t have internet connection, you probably installed HDP using a local repo. If so, you should already have access to zeppelin rpm. You can check this by running:
yum search zeppelin

If so, you can
1. download the Ambari service definition for Zeppelin from https://github.com/hortonworks-gallery/ambari-zeppelin-service/archive/master.zip
2. unzip under /var/lib/ambari-server/resources/stacks/HDP/2.4/services/ZEPPELIN (you will have to create this dir).
3. Now you should have a configuration and package subdir under /var/lib/ambari-server/resources/stacks/HDP/2.4/services/ZEPPELIN
4. Restart ambari-server
5. Install Zeppelin via Ambari as you would install any other service via the ‘Add service wizard'

See here for more info:
https://community.hortonworks.com/questions/26215/zeppelin-offline-installation.html

Thanks
Ali


On Apr 11, 2016, at 9:59 PM, analog76 <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi,

I would like to deploy the zeppelin service in the HDP 2.4 platform.

My data platform doesn't have internet connection or git on that host. How do I deploy this on that platform ?

Here the steps are not correct or I am missing something.

VERSION=hdp-select status hadoop-client | sed 's/hadoop-client - \([0-9]\.[0-9]\).*/\1/'

sudo git clone https://github.com/hortonworks-gallery/ambari-zeppelin-service.git /var/lib/ambari-server/resources/stacks/HDP/$VERSION/services/ZEPPELIN

**Comment by abajwa-hw** [comment]
Have also added these steps to the end of the README:
https://github.com/hortonworks-gallery/ambari-zeppelin-service/blob/master/README.md#offline-install-on-cluster

**Comment by analog76** [comment]
Thanks for the update. 

I figured it out in another way.  git cloned in my laptop and moved to the ambari-server host.

mv ZEPPELIN /var/lib/ambari-server/resources/stacks/HDP/$VERSION/services/

where ZEPPELIN =downloaded ambari-zeppelin-service folder.


I will also test you had documented.
