### ISSUE TITLE
Error installing on ubuntu

### ISSUE THREAD

**Issue by hardboy111** [hortonworks-gallery/ambari-zeppelin-service#24]
Hi,

I'm getting the following error when performing the install:

`resource_management.core.exceptions.Fail: Execution of '/usr/bin/apt-get -q -o Dpkg::Options::=--force-confdef --allow-unauthenticated --assume-yes install zeppelin' returned 100. Reading package lists...
Building dependency tree...
Reading state information...
zeppelin is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 92 not upgraded.
2 not fully installed or removed.
After this operation, 0 B of additional disk space will be used.
Setting up zeppelin-2-4-0-0-169 (0.6.0.2.4.0.0-169) ...
update-alternatives: error: alternative path /etc/zeppelin/conf.dist doesn't exist
dpkg: error processing package zeppelin-2-4-0-0-169 (--configure):
 subprocess installed post-installation script returned error exit status 2
dpkg: dependency problems prevent configuration of zeppelin:
 zeppelin depends on zeppelin-2-4-0-0-169; however:
  Package zeppelin-2-4-0-0-169 is not configured yet.

dpkg: error processing package zeppelin (--configure):
 dependency problems - leaving unconfigured
No apport report written because the error message indicates its a followup error from a previous failure.
Errors were encountered while processing:
 zeppelin-2-4-0-0-169
 zeppelin
E: Sub-process /usr/bin/dpkg returned an error code (1)`

Any ideas how I can fix this? Looks like a cyclical dependency issue perhaps? I tried to install the zeppelin package before installing  zeppelin-2-4-0-0-169 package but didnt help.

M

**Comment by hardboy111** [comment]
Just for anyone else trying to install on ubuntu - I fixed this b:
- deleting the zeppelin service from ambari (i.e. curl -u admin:admin -H "X-Requested-By: ambari" -X DELETE  http://AMBARI_SERVER_HOST:8080/api/v1/clusters/c1/services/SERVICENAME)

- purge zeppelin & zeppelin-2-4-0-0-169 packages
- create /etc/zeppelin/conf.dist/ folder and copy in conf/ folder from apache zeppelin-incubator git source
- create /var/lib/zeppelin manually

Then run the Zeppelin install again through ambari using 'Add Service'

**Comment by gakuba** [comment]
Thanks @hardboy111  that helped a lot. I didn't have to purge the packages though. Here are steps I followed:
 
1. Create /var/lib/zeppelin directory
2. Create /etc/zeppelin/conf.dist/ folder and copy in conf/ folder from apache zeppelin-incubator git source (https://github.com/apache/zeppelin)
3.Delete the zeppelin service from ambari (i.e. curl -u admin:admin -H "X-Requested-By: ambari" -X DELETE http://AMBARI_SERVER_HOST:8080/api/v1/clusters/c1/services/SERVICENAME)
4. restart ambari server (ambari-server restart)
5. Add zeppelin service as you would add any other services from ambari dashboard.

**Comment by fabsta** [comment]
Thanks, @hardboy111 ! That worked for me!
