### ISSUE TITLE
Run button 

### ISSUE THREAD

**Issue by idir-ait** [hortonworks-gallery/ambari-zeppelin-service#25]
Hello all
I wanna know it's possible to run paragraph code with un angular button ? 
thx :)

**Comment by abajwa-hw** [comment]
Could you post this question on http://community.hortonworks.com ?

Sent from my iPhone

On Apr 16, 2016, at 4:59 AM, idir <notifications@github.com<mailto:notifications@github.com>> wrote:


Hello all
I wanna know it's possible to run paragraph code with un angular button ?
thx :)

-
