### ISSUE TITLE
Unknow error when deploy 

### ISSUE THREAD

**Issue by fjgarciamacias** [hortonworks-gallery/ambari-zeppelin-service#32]
I'm trying to install zeppelin according this link `https://community.hortonworks.com/articles/34424/apache-zeppelin-on-hdp-242.html`, but the deploy process fails and show the following error:

```
Traceback (most recent call last):
  File "/var/lib/ambari-agent/cache/stacks/HDP/2.4/services/ZEPPELIN/package/scripts/master.py", line 236, in <module>
    Master().execute()
  File "/usr/lib/python2.6/site-packages/resource_management/libraries/script/script.py", line 219, in execute
    method(env)
  File "/var/lib/ambari-agent/cache/stacks/HDP/2.4/services/ZEPPELIN/package/scripts/master.py", line 65, in install
    recursive_ownership=True                  
  File "/usr/lib/python2.6/site-packages/resource_management/core/base.py", line 113, in __new__
    cls(name.pop(0), env, provider, **kwargs)
  File "/usr/lib/python2.6/site-packages/resource_management/core/base.py", line 146, in __init__
    raise Fail("%s received unsupported argument %s" % (self, key))
resource_management.core.exceptions.Fail: Directory['/var/run/zeppelin-notebook'] received unsupported argument create_parents
```

I've been searching for a solution without success, I'm using Ambari Version 2.2.1.1, HDP 2.4.3.0-227, Python 2.6 and CENTOS 7. I hope someone can help me, thanks.

**Comment by DimaKovalyov** [comment]
I second that.
fjgarciamacias, were you able to resolve this?

- Dima

**Comment by DimaKovalyov** [comment]
I noticed this thread:
[](https://github.com/spring-cloud/spring-cloud-dataflow-ambari-rpm/issues/20)
And from it was able to guess that I need to remove these two lines (that are required for supporting HDP 2.5):
```
create_parents = True
recursive_ownership=True

```From following files:
```
/var/lib/ambari-server/resources/stacks/HDP/2.4/services/ZEPPELIN/package/scripts/master.py
/var/lib/ambari-agent/cache/stacks/HDP/2.4/services/ZEPPELIN/package/scripts/master.py
/var/lib/ambari-server/resources/stacks/HDP/hadoop-client - 2.4.3.0-227/services/ZEPPELIN/package/scripts/master.py

```
After this I was able to install Zeppelin for HDP 2.4.

**Comment by ebuildy** [comment]
This is since this commit I believe:

https://github.com/hortonworks-gallery/ambari-zeppelin-service/commit/a6701c5e639663b615592f5506c7c297d1553b67
