### ISSUE TITLE
Authentication

### ISSUE THREAD

**Issue by deepakas** [hortonworks-gallery/ambari-zeppelin-service#6]
I installed the zeppelin service through Ambari. But it is not authenticated with the users. Do we need to enable any settings to authenticate Zeppeling with users in Ambari?

**Comment by deepakas** [comment]
Also for some reason the link from Ambari view menu is not working eventhough I copied the jar from the machine where zeppelin was installed.

**Comment by abajwa-hw** [comment]
By default, the view will use the internal hostname. So if you setup on VM or cloud you will need to create local hosts entry to access
To change this behavior when you are installing zeppelin, set the public name property to the public name or public IP of the node running Zeppelin. See README for more details


  *   public name: This is used to setup the Ambari view for Zeppelin. Set this to the public host/IP of zeppelin node (which must must be reachable from your local machine). If installing on sandbox (or local VM), change this to the IP address of VM. If installing on cloud, set this to public name/IP of zeppelin node. Alternatively, if you already have a local hosts file entry for the internal hostname of the zeppelin node (e.g. sandbox.hortonworks.com<http://sandbox.hortonworks.com>), you can leave this empty - it will default to internal hostname


On Oct 20, 2015, at 10:47 AM, deepakas <notifications@github.com<mailto:notifications@github.com>> wrote:


Also for some reason the link from Ambari view menu is not working eventhough I copied the jar from the machine where zeppelin was installed.
