### ISSUE TITLE
Service install wizard

### ISSUE THREAD

**Issue by blitzbs** [hortonworks-gallery/ambari-zeppelin-service#8]
OS : Centos 7 
Cluster of 5 servers + 1 Ambari server (2.1.1)

Hi there,

To begin, thanks you for your work for the integration in Ambari UI.

My issue:

After had the git in the services directory and restart Ambari server, when I add the service the wizard stay on step 4 with "loading". I tried twice again and same result.

Do you have any suggestion ?

I check on ambari-server.log and no clue...

Have a nive day :)

**Comment by abajwa-hw** [comment]
Thanks @blitzbs. I just tested on a single node Centos 7 setup with Ambari 2.1.2 / HDP 2.3.2.0-2950 / Spark 1.4.1.2.3.2.0-2950 and was able to install Zeppelin successfully. Could you try to open an incognito window and re-try? Wondering if there is a browser caching issue.

**Comment by blitzbs** [comment]
Hi, I tried the incognito way but no change.

After the step "Assign Masters", I see "Assign slaves and clients" very quickly (less than 1 sec). Then step "Customize Services" : "Loading...".

My brother is Firefox 42.0 Ubuntu, I'm going to try on Windows IE (lol).

**Comment by abajwa-hw** [comment]
I wonder if it is a bug with Ambari 2.1.1 then. Any chance you can try with Ambari 2.1.2?

On Nov 30, 2015, at 11:59 PM, blitzbs <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi, I tried the incognito way but no change.

After the step "Assign Masters", I see "Assign slaves and clients" very quickly (less than 1 sec). Then step "Customize Services" : "Loading...".

My brother is Firefox 42.0 Ubuntu, I'm going to try on Windows IE (lol).

**Comment by blitzbs** [comment]
Thx for your answer, I'm going to update Ambari.

**Comment by blitzbs** [comment]
I have just upgraded and unfortunately the issue is still there.
I still go on finding any clue.

Benjamin DEBARBIEUX

   - tél : +33 (0)4 74 96 88 17
   - fax : +33 (0)4 74 96 31 88
   - email : bdebarbieux@blitzbs.com

BLITZ BUSINESS SERVICE


2015-12-01 9:15 GMT+01:00 Ali Bajwa <notifications@github.com>:

> I wonder if it is a bug with Ambari 2.1.1 then. Any chance you can try
> with Ambari 2.1.2?
>
> On Nov 30, 2015, at 11:59 PM, blitzbs <notifications@github.com<mailto:

**Comment by blitzbs** [comment]
Hello,

Some news : 

After a wipe of my cluster, I could reinstall successfully the package. 
I have found the origin of the issue. It isn't  a Zeppelin issuer, it is js delay when the "customize services" load. With other native package, I have the same issue and after looking for the reason I find Firefox warning with sometime popup "do you want to kill the script js".

Thanks you again for your work, It runs like a charm !

If I can just say one thing (not a bug), the Zeppelin view is not "full screen", it's a frame in Ambari page => 2 scrollbar on the right side...

**Comment by blitzbs** [comment]
Hello,

Some news : 

After a wipe of my cluster, I could reinstall successfully the package. 

I have found the origin of the issue. It isn't  a Zeppelin issue, it is a javascript delay when the "customize services" lpart oad. With other native package, I have the same issue and after looking for the reason I find Firefox warning with sometimes popup "do you want to kill the script js".

Thanks you again for your work, It runs like a charm !

If I can just say one thing (not a bug), the Zeppelin view is not "full screen", it's a frame in Ambari page => 2 scrollbar on the right side...

I close the issue .
